version: "3.8"

services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_GOOGLE_MAP_KEY=AIzaSyAyh4foZcK_Kcmv8w-yhH0tsJk1XZGu9cU
      - NEXT_PUBLIC_GEMINI_API_KEY=AIzaSyB91q6_m5LJlGpH4-TuS1NRS4rqFDkD_Lw
      # Ubah URL API menggunakan nama service
      - NEXT_PUBLIC_API_URL=http://be:5000/api
    volumes:
      - ./fe:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - be
    networks:
      - app_network

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_USER=postgres
      - DB_HOST=db
      - DB_DATABASE=triptix
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_MAP_KEY=${GOOGLE_MAP_KEY}
    volumes:
      - ./be:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=triptix
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  # Tambahkan service NGROK
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTH=${NGROK_AUTH_TOKEN} # Tambahkan token NGROK Anda di .env
      - NGROK_PROTOCOL=http
      - NGROK_PORT=web:80 # Arahkan ke service nginx
    depends_on:
      - web
    networks:
      - app_network

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - be
    networks:
      - app_network

  nagios:
    image: jasonrivers/nagios:latest
    ports:
      - "8080:80"
    environment:
      - NAGIOSADMIN_USER=nagiosadmin
      - NAGIOSADMIN_PASS=nagios123
    volumes:
      - ./nagios_etc:/opt/nagios/etc
      - ./nagios_var:/opt/nagios/var
      - ./nagios/custom-plugins:/opt/Custom-Nagios-Plugins
    depends_on:
      - frontend
      - be
      - db
    networks:
      - app_network
    privileged: true

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  npm_data:
  letsencrypt:
  nagios_etc:
  nagios_var:
